// <auto-generated />
using System;
using BankSim.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankSim.Shared.Data.Migrations
{
    [DbContext(typeof(BankSimContext))]
    partial class BankSimContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankSim.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BankSim.Models.Contas.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<float>("Saldo")
                        .HasColumnType("real");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contas");

                    b.HasDiscriminator<string>("TipoConta").HasValue("Conta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BankSim.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContaDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("ContaOrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_Hora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinoId");

                    b.HasIndex("ContaOrigemId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("BankSim.Models.Contas.ContaCorrente", b =>
                {
                    b.HasBaseType("BankSim.Models.Contas.Conta");

                    b.HasDiscriminator().HasValue("Corrente");
                });

            modelBuilder.Entity("BankSim.Models.Contas.ContaPoupanca", b =>
                {
                    b.HasBaseType("BankSim.Models.Contas.Conta");

                    b.HasDiscriminator().HasValue("Poupanca");
                });

            modelBuilder.Entity("BankSim.Models.Contas.Conta", b =>
                {
                    b.HasOne("BankSim.Models.Cliente", "Cliente")
                        .WithMany("Contas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BankSim.Models.Transacao", b =>
                {
                    b.HasOne("BankSim.Models.Contas.Conta", "ContaDestino")
                        .WithMany("TransacoesRecebidas")
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BankSim.Models.Contas.Conta", "ContaOrigem")
                        .WithMany("TransacoesEnviadas")
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");
                });

            modelBuilder.Entity("BankSim.Models.Cliente", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("BankSim.Models.Contas.Conta", b =>
                {
                    b.Navigation("TransacoesEnviadas");

                    b.Navigation("TransacoesRecebidas");
                });
#pragma warning restore 612, 618
        }
    }
}
